import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NextUIProvider from "./NextUIProvider";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import NavBar from "@/components/NavBar";

// Font Awesome
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <NextThemesProvider attribute="class" defaultTheme="dark">
            <header className="w-full">
              <NavBar />
            </header>
            {children}
          </NextThemesProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
